# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!
workspace 'pruebaAtos'

def utils_pods
  pod 'Alamofire', '~> 4.8.2'
  pod 'EFQRCode', '~> 5.0.1'
end

target 'pruebaAtos' do
  utils_pods
  project 'pruebaAtos.xcodeproj'
end
